CLASSIFIER_PROMPT = """Classify this voice input as either:
- command: Desktop control actions (open/close apps, window operations, mouse/keyboard, screenshots, colors, volume/audio control, media playback, system settings)
- conversation: Questions, chat, help requests, explanations, general knowledge

Examples of COMMAND:
- "open firefox"
- "close text editor"
- "describe screen"
- "maximize window"
- "scroll down"
- "drag from left to right"
- "screenshot the window"
- "pick color at 500 300"
- "what color is at position 800 400"
- "click at 100 200"
- "switch to workspace 2"
- "type hello world"
- "press ctrl c"
- "enable automation"
- "disable automation"
- "turn on automation"
- "turn off automation"
- "clean up screenshots"
- "delete screenshots"
- "set volume to 50"
- "increase volume by 10"
- "decrease volume"
- "turn volume up"
- "turn volume down"
- "mute"
- "unmute"
- "mute volume"
- "unmute volume"
- "play"
- "pause"
- "play track"
- "pause track"
- "playtrack"
- "next track"
- "previous track"
- "skip"
- "skip track"
- "play music"
- "pause music"
- "next song"
- "previous song"
- "stop music"
- "turn on dark mode"
- "turn off dark mode"
- "enable dark mode"
- "disable dark mode"
- "switch to light mode"
- "turn on night light"
- "turn off night light"
- "enable do not disturb"
- "disable do not disturb"
- "turn on wifi"
- "turn off wifi"
- "enable bluetooth"
- "disable bluetooth"
- "open google.com"
- "go to github.com"
- "open https://example.com"
- "open screenshot.png"
- "open screenshot in pictures"
- "open report.pdf"
- "open ~/Documents/report.pdf"
- "find all PDFs"
- "search for screenshots"
- "where are my tax documents"
- "list installed applications"
- "show installed apps"
- "what apps are installed"
- "notify me in 5 minutes"
- "remind me about meeting"
- "send notification"
- "alert me in 1 hour"
- "cleanup screenshots"
- "remove screenshots"
- "list workspaces"
- "switch to workspace 1"

Examples of CONVERSATION:
- "what is docker"
- "how do I install nodejs"
- "tell me about python"
- "what's the weather"
- "explain kubernetes"
- "what does this code do"

Input: "{user_input}"

Reply with ONE word only: command or conversation"""

COMMAND_SYSTEM_MSG = "You are a silent system orchestrator. Your ONLY job is to execute tool calls based on user intent. DO NOT output conversational text. DO NOT confirm actions. DO NOT be polite. If you need to use a tool, output ONLY the tool call. FORGET gedit and USE gnome-text-editor. When a command requires multiple steps, make tool calls one at a time. After receiving tool results, either make another tool call or return a brief spoken summary. Keep summaries under 2 sentences."

CONVERSATION_PROMPT = """You are a helpful AI assistant.
Answer questions clearly and concisely.
Keep responses under 3 sentences unless more detail is requested.
Be friendly and informative."""
